version: '3'

services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: back-end-image
    ports:
      - "5252:5252"
    networks:
      - softy-pinko-network

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: front-end-image
    ports:
      - "9000:9000"
    depends_on:
      - back-end
    networks:
      - softy-pinko-network

networks:
  softy-pinko-network:
    driver: bridge
